//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.12 at 06:09:17 PM CET 
//


package com.example.danceschool.raspored;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.danceschool.raspored package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.danceschool.raspored
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllSchedulesRequest }
     * 
     */
    public GetAllSchedulesRequest createGetAllSchedulesRequest() {
        return new GetAllSchedulesRequest();
    }

    /**
     * Create an instance of {@link GetAllSchedulesResponse }
     * 
     */
    public GetAllSchedulesResponse createGetAllSchedulesResponse() {
        return new GetAllSchedulesResponse();
    }

    /**
     * Create an instance of {@link RasporedType }
     * 
     */
    public RasporedType createRasporedType() {
        return new RasporedType();
    }

    /**
     * Create an instance of {@link GetSchedulesByClassTypeRequest }
     * 
     */
    public GetSchedulesByClassTypeRequest createGetSchedulesByClassTypeRequest() {
        return new GetSchedulesByClassTypeRequest();
    }

    /**
     * Create an instance of {@link GetSchedulesByClassTypeResponse }
     * 
     */
    public GetSchedulesByClassTypeResponse createGetSchedulesByClassTypeResponse() {
        return new GetSchedulesByClassTypeResponse();
    }

    /**
     * Create an instance of {@link AddScheduleRequest }
     * 
     */
    public AddScheduleRequest createAddScheduleRequest() {
        return new AddScheduleRequest();
    }

    /**
     * Create an instance of {@link AddScheduleResponse }
     * 
     */
    public AddScheduleResponse createAddScheduleResponse() {
        return new AddScheduleResponse();
    }

    /**
     * Create an instance of {@link DeleteScheduleRequest }
     * 
     */
    public DeleteScheduleRequest createDeleteScheduleRequest() {
        return new DeleteScheduleRequest();
    }

    /**
     * Create an instance of {@link DeleteScheduleResponse }
     * 
     */
    public DeleteScheduleResponse createDeleteScheduleResponse() {
        return new DeleteScheduleResponse();
    }

}
