//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.12 at 06:09:17 PM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://danceschool.example.com/raspored", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.danceschool.raspored;
