//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.08 at 04:58:50 PM CET 
//


package com.example.danceschool.raspored;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RasporedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RasporedType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="tipCasa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="datumVreme" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="trajanjeMin" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="lokacija" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="opis" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="instruktorId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="instruktorIme" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RasporedType", propOrder = {
    "id",
    "tipCasa",
    "datumVreme",
    "trajanjeMin",
    "lokacija",
    "opis",
    "instruktorId",
    "instruktorIme"
})
public class RasporedType {

    protected long id;
    @XmlElement(required = true)
    protected String tipCasa;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datumVreme;
    protected int trajanjeMin;
    protected String lokacija;
    protected String opis;
    protected long instruktorId;
    protected String instruktorIme;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the tipCasa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipCasa() {
        return tipCasa;
    }

    /**
     * Sets the value of the tipCasa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipCasa(String value) {
        this.tipCasa = value;
    }

    /**
     * Gets the value of the datumVreme property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumVreme() {
        return datumVreme;
    }

    /**
     * Sets the value of the datumVreme property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumVreme(XMLGregorianCalendar value) {
        this.datumVreme = value;
    }

    /**
     * Gets the value of the trajanjeMin property.
     * 
     */
    public int getTrajanjeMin() {
        return trajanjeMin;
    }

    /**
     * Sets the value of the trajanjeMin property.
     * 
     */
    public void setTrajanjeMin(int value) {
        this.trajanjeMin = value;
    }

    /**
     * Gets the value of the lokacija property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLokacija() {
        return lokacija;
    }

    /**
     * Sets the value of the lokacija property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLokacija(String value) {
        this.lokacija = value;
    }

    /**
     * Gets the value of the opis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpis() {
        return opis;
    }

    /**
     * Sets the value of the opis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpis(String value) {
        this.opis = value;
    }

    /**
     * Gets the value of the instruktorId property.
     * 
     */
    public long getInstruktorId() {
        return instruktorId;
    }

    /**
     * Sets the value of the instruktorId property.
     * 
     */
    public void setInstruktorId(long value) {
        this.instruktorId = value;
    }

    /**
     * Gets the value of the instruktorIme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstruktorIme() {
        return instruktorIme;
    }

    /**
     * Sets the value of the instruktorIme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstruktorIme(String value) {
        this.instruktorIme = value;
    }

}
